name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  PyPi:
    name: Build and publish wheels to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hours
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.5.1

      - name: Install Python dependencies
        run: poetry install --with dev

      - name: Build package
        run: poetry build -f wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist

  Github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.5.1

      - name: Install Python dependencies
        run: poetry install --with dev

      - name: Build package
        run: poetry build -f wheel
      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl

      - name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v2
        with:
          command: query
          version: latest

      - name: Display release info
        run: |
          echo "# v${{ steps.query-release-info.outputs.version }}\n" > release.md
          echo "\n${{ steps.query-release-info.outputs.release-date }}\n\n" >> release.md
          echo "${{ steps.query-release-info.outputs.release-notes }}\n" >> release.md

      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          body_path: release.md
